include:
  - component: gitlab.partner.bdr.de/innersrc/ci/sbom-vun/post-build@main
    inputs:
      stage: sbom-ci
      artifact-job: build
      artifact-path: .

syft:create:sbom:
  variables:
    GIT_STRATEGY: fetch

trivy:create:sbom:
  variables:
    GIT_STRATEGY: fetch

collect_artifacts:
  stage: package
  image: partner.bdr.de/docker-remote/maven:3.9.9-eclipse-temurin-21
  needs:
    - job: "trivy:create:sbom"
      artifacts: true
    - job: "syft:create:sbom"
      artifacts: true
    - job: "trivy:scan:sbom: [trivy, $TRIVY_SBOM]"
      artifacts: true
    - job: "grype:scan:sbom: [syft, $SYFT_SBOM]"
      artifacts: true
    - job: "grype:scan:sbom: [trivy, $TRIVY_SBOM]"
      artifacts: true
    - job: "licenses: [syft, $SYFT_SBOM]"
      artifacts: true
  script:
    - tar -czf sbom_reports.tar.gz reports/
    #- if [ -z $CI_COMMIT_TAG ]; then SBOM_PACKAGE="elefand-maven-staging"; else SBOM_PACKAGE="elefand-maven-final"; fi
    #- curl -u "$ARTIFACTORY_ACC_KEY" -X PUT "https://partner.bdr.de/artifactory/$SBOM_PACKAGE/SBOM(Android-Preprod)/$CI_COMMIT_BRANCH/reports/sbom_reports.tar.gz" -T "sbom_reports.tar.gz"
  artifacts:
    paths:
      - sbom_reports.tar.gz